/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import type {
  Customer,
  CustomerPricingAgreement,
  Product,
  Order,
  OrderItem,
  Payment,
  Expense,
  Complaint
} from '../types/domain.ts';

export const initialProducts: Product[] = [
  {
    id: 'prod-1',
    nameEn: 'Burger Bread With Egg',
    nameAm: 'እንቁላል የተቀባ',
    descriptionEn: 'Golden glazed soft bun with egg wash finish',
    descriptionAm: 'ለስላሳ በእንቁላል የተቀባ የበርገር ዳቦ',
    basePrice: 25,
    category: 'Burger Bread',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-2',
    nameEn: 'Burger Bread Without Egg',
    nameAm: 'እንቁላል ያልተቀባ',
    descriptionEn: 'Standard burger bun without egg wash',
    descriptionAm: 'እንቁላል ያልተቀባ መደበኛ የበርገር ዳቦ',
    basePrice: 22,
    category: 'Burger Bread',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-3',
    nameEn: 'Normal Bread',
    nameAm: 'መደበኛ ዳቦ',
    descriptionEn: 'Traditional daily table bread loaf',
    descriptionAm: 'የዕለት መደበኛ የጠረጴዛ ዳቦ',
    basePrice: 15,
    category: 'Table Bread',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-4',
    nameEn: 'Feta Bread',
    nameAm: 'ፈታ ዳቦ',
    descriptionEn: 'Artisanal loaf baked with savory feta cheese filling',
    descriptionAm: 'በጣፋጭ ፈታ አይብ የተዘጋጀ ልዩ ዳቦ',
    basePrice: 35,
    category: 'Specialty Bread',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
  },
  {
    id: 'prod-5',
    nameEn: 'Sesame Bun',
    nameAm: 'ሰሊጥ ያለበት ዳቦ',
    descriptionEn: 'Aromatic burger bun topped with roasted sesame',
    descriptionAm: 'በጥብስ ሰሊጥ ያጌጠ ለስላሳ ዳቦ',
    basePrice: 28,
    category: 'Burger Bread',
    isActive: true,
    createdAt: '2026-02-15T00:00:00Z',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'cust-1',
    name: 'Solomon Tadesse',
    organizationName: 'ABC Burger House',
    branch: 'Bole Atlas Branch',
    customerType: 'BURGER_HOUSE',
    phone: '0911234567',
    managerPhone: '0922114455',
    address: 'Bole Atlas, next to Edna Mall road',
    status: 'ACTIVE',
    preferredDeliveryTime: '07:30 AM',
    notes: 'Morning priority delivery. Always requires delivery receipt.',
    regularPreferences: [
      { productId: 'prod-1', regularQuantity: 120 },
      { productId: 'prod-2', regularQuantity: 50 },
    ],
    createdAt: '2026-01-10T08:00:00Z',
    updatedAt: '2026-09-20T10:00:00Z',
  },
  {
    id: 'cust-2',
    name: 'Alemayehu Kebede',
    organizationName: 'Yod Abyssinia Restaurant',
    branch: 'Bole Medhanealem',
    customerType: 'RESTAURANT',
    phone: '0912345678',
    managerPhone: '0911998877',
    address: 'Bole Medhanealem, Cameroon Street',
    status: 'ACTIVE',
    preferredDeliveryTime: '08:00 AM',
    notes: 'Large daily orders. Normal bread and Feta bread in high demand.',
    regularPreferences: [
      { productId: 'prod-3', regularQuantity: 150 },
      { productId: 'prod-4', regularQuantity: 40 },
    ],
    createdAt: '2026-01-15T09:30:00Z',
    updatedAt: '2026-09-22T14:00:00Z',
  },
  {
    id: 'cust-3',
    name: 'Bethlehem Haile',
    organizationName: "Kaldi's Cafe & Bistro",
    branch: 'Kazanchis Branch',
    customerType: 'CAFE',
    phone: '0923456789',
    address: 'Kazanchis, across UNECA main gate',
    status: 'ACTIVE',
    preferredDeliveryTime: '07:00 AM',
    notes: 'Requires delivery before morning rush.',
    regularPreferences: [
      { productId: 'prod-1', regularQuantity: 80 },
      { productId: 'prod-4', regularQuantity: 25 },
    ],
    createdAt: '2026-02-01T11:00:00Z',
    updatedAt: '2026-09-23T08:15:00Z',
  },
  {
    id: 'cust-4',
    name: 'Dawit Worku',
    organizationName: 'Stadium Fresh Burgers',
    branch: 'Meskel Square',
    customerType: 'BURGER_HOUSE',
    phone: '0934567890',
    address: 'Meskel Square, Stadium entrance',
    status: 'ACTIVE',
    preferredDeliveryTime: '09:00 AM',
    notes: 'Special price contract for unglazed burger bread.',
    regularPreferences: [
      { productId: 'prod-2', regularQuantity: 140 },
    ],
    createdAt: '2026-02-10T12:00:00Z',
    updatedAt: '2026-09-21T16:30:00Z',
  },
  {
    id: 'cust-5',
    name: 'Tigist Assefa',
    organizationName: 'Olympia Corner Shop',
    branch: 'Olympia',
    customerType: 'SHOP',
    phone: '0945678901',
    address: 'Bole Olympia, behind Total station',
    status: 'ACTIVE',
    preferredDeliveryTime: '06:30 AM',
    notes: 'Daily retail resale. Regular Normal Bread.',
    regularPreferences: [
      { productId: 'prod-3', regularQuantity: 80 },
    ],
    createdAt: '2026-03-01T10:00:00Z',
    updatedAt: '2026-09-22T09:00:00Z',
  },
];

export const initialPricingAgreements: CustomerPricingAgreement[] = [
  {
    id: 'cpa-1',
    customerId: 'cust-1', // ABC Burger House
    productId: 'prod-1',  // Burger Bread With Egg (Base: 25)
    agreedPrice: 22,
    effectiveDate: '2026-02-01T00:00:00Z',
    isActive: true,
    notes: 'High volume wholesale agreement (100+ units daily)',
  },
  {
    id: 'cpa-2',
    customerId: 'cust-4', // Stadium Fresh Burgers
    productId: 'prod-2',  // Burger Bread Without Egg (Base: 22)
    agreedPrice: 19,
    effectiveDate: '2026-03-01T00:00:00Z',
    isActive: true,
    notes: 'Long term partnership contract',
  },
  {
    id: 'cpa-3',
    customerId: 'cust-2', // Yod Abyssinia
    productId: 'prod-3',  // Normal Bread (Base: 15)
    agreedPrice: 13,
    effectiveDate: '2026-02-15T00:00:00Z',
    isActive: true,
    notes: 'Bulk purchase discount',
  },
];

// Today's date ISO string reference for relative data
const todayStr = '2026-09-24';
const yesterdayStr = '2026-09-23';

export const initialOrders: Order[] = [
  {
    id: 'ord-101',
    orderNumber: 'ORD-101',
    customerId: 'cust-1',
    customerName: 'Solomon Tadesse',
    organizationName: 'ABC Burger House',
    branch: 'Bole Atlas Branch',
    customerPhone: '0911234567',
    orderSource: 'PHONE',
    status: 'DELIVERED',
    orderDate: `${todayStr}T06:30:00Z`,
    totalAmount: 3740, // (120 * 22) + (50 * 22) = 2640 + 1100 = 3740
    deliveryType: 'DELIVERY',
    deliveryAddress: 'Bole Atlas, next to Edna Mall road',
    scheduledTime: '07:30 AM',
    actualDeliveryTime: '07:25 AM',
    driverName: 'Kebede Haile (Motor 1)',
    deliveryNotes: 'Delivered to kitchen manager. Signature received.',
    notes: 'Morning phone order taken by owner.',
    createdBy: 'Owner',
    updatedAt: `${todayStr}T07:30:00Z`,
  },
  {
    id: 'ord-102',
    orderNumber: 'ORD-102',
    customerId: 'cust-2',
    customerName: 'Alemayehu Kebede',
    organizationName: 'Yod Abyssinia Restaurant',
    branch: 'Bole Medhanealem',
    customerPhone: '0912345678',
    orderSource: 'PHONE',
    status: 'OUT_FOR_DELIVERY',
    orderDate: `${todayStr}T07:15:00Z`,
    totalAmount: 3350, // (150 * 13) + (40 * 35) = 1950 + 1400 = 3350
    deliveryType: 'DELIVERY',
    deliveryAddress: 'Bole Medhanealem, Cameroon Street',
    scheduledTime: '08:15 AM',
    driverName: 'Getachew Bekele (Van 2)',
    deliveryNotes: 'In transit along Cameroon Street.',
    notes: 'Customer called at 07:15 AM requesting prompt delivery.',
    createdBy: 'Owner',
    updatedAt: `${todayStr}T07:45:00Z`,
  },
  {
    id: 'ord-103',
    orderNumber: 'ORD-103',
    customerId: 'cust-3',
    customerName: 'Bethlehem Haile',
    organizationName: "Kaldi's Cafe & Bistro",
    branch: 'Kazanchis Branch',
    customerPhone: '0923456789',
    orderSource: 'PHONE',
    status: 'READY',
    orderDate: `${todayStr}T07:40:00Z`,
    totalAmount: 2875, // (80 * 25) + (25 * 35) = 2000 + 875 = 2875
    deliveryType: 'DELIVERY',
    deliveryAddress: 'Kazanchis, across UNECA main gate',
    scheduledTime: '08:45 AM',
    driverName: 'Kebede Haile (Motor 1)',
    deliveryNotes: 'Packed in thermal crates.',
    notes: 'Phone order. Customer confirmed bread is for morning sandwiches.',
    createdBy: 'Order Staff',
    updatedAt: `${todayStr}T08:00:00Z`,
  },
  {
    id: 'ord-104',
    orderNumber: 'ORD-104',
    customerId: 'cust-4',
    customerName: 'Dawit Worku',
    organizationName: 'Stadium Fresh Burgers',
    branch: 'Meskel Square',
    customerPhone: '0934567890',
    orderSource: 'PHONE',
    status: 'PREPARING',
    orderDate: `${todayStr}T08:05:00Z`,
    totalAmount: 2660, // 140 * 19 (agreed price) = 2660
    deliveryType: 'DELIVERY',
    deliveryAddress: 'Meskel Square, Stadium entrance',
    scheduledTime: '09:30 AM',
    deliveryNotes: 'Requires second batch baking.',
    notes: 'Phone order placed by manager Dawit.',
    createdBy: 'Owner',
    updatedAt: `${todayStr}T08:10:00Z`,
  },
  {
    id: 'ord-105',
    orderNumber: 'ORD-105',
    customerId: 'cust-5',
    customerName: 'Tigist Assefa',
    organizationName: 'Olympia Corner Shop',
    branch: 'Olympia',
    customerPhone: '0945678901',
    orderSource: 'PHONE',
    status: 'DELIVERED',
    orderDate: `${todayStr}T05:50:00Z`,
    totalAmount: 1200, // 80 * 15 = 1200
    deliveryType: 'DELIVERY',
    deliveryAddress: 'Bole Olympia, behind Total station',
    scheduledTime: '06:30 AM',
    actualDeliveryTime: '06:20 AM',
    driverName: 'Getachew Bekele (Van 2)',
    deliveryNotes: 'Dropped at shop front.',
    notes: 'Early morning regular delivery.',
    createdBy: 'Order Staff',
    updatedAt: `${todayStr}T06:20:00Z`,
  },
  // Yesterday's order with debt/partial payment
  {
    id: 'ord-098',
    orderNumber: 'ORD-098',
    customerId: 'cust-1',
    customerName: 'Solomon Tadesse',
    organizationName: 'ABC Burger House',
    branch: 'Bole Atlas Branch',
    customerPhone: '0911234567',
    orderSource: 'PHONE',
    status: 'DELIVERED',
    orderDate: `${yesterdayStr}T06:30:00Z`,
    totalAmount: 4400, // 200 * 22 = 4400
    deliveryType: 'DELIVERY',
    deliveryAddress: 'Bole Atlas, next to Edna Mall road',
    scheduledTime: '07:30 AM',
    actualDeliveryTime: '07:28 AM',
    driverName: 'Kebede Haile (Motor 1)',
    notes: 'Large catering event burger bun order.',
    createdBy: 'Owner',
    updatedAt: `${yesterdayStr}T07:30:00Z`,
  },
];

export const initialOrderItems: OrderItem[] = [
  // Items for ord-101 (ABC Burger House)
  {
    id: 'item-1',
    orderId: 'ord-101',
    productId: 'prod-1',
    productNameEn: 'Burger Bread With Egg',
    productNameAm: 'እንቁላል የተቀባ',
    quantity: 120,
    unitPrice: 22, // Agreed price applied
    subtotal: 2640,
  },
  {
    id: 'item-2',
    orderId: 'ord-101',
    productId: 'prod-2',
    productNameEn: 'Burger Bread Without Egg',
    productNameAm: 'እንቁላል ያልተቀባ',
    quantity: 50,
    unitPrice: 22, // Base price
    subtotal: 1100,
  },
  // Items for ord-102 (Yod Abyssinia)
  {
    id: 'item-3',
    orderId: 'ord-102',
    productId: 'prod-3',
    productNameEn: 'Normal Bread',
    productNameAm: 'መደበኛ ዳቦ',
    quantity: 150,
    unitPrice: 13, // Agreed price applied
    subtotal: 1950,
  },
  {
    id: 'item-4',
    orderId: 'ord-102',
    productId: 'prod-4',
    productNameEn: 'Feta Bread',
    productNameAm: 'ፈታ ዳቦ',
    quantity: 40,
    unitPrice: 35,
    subtotal: 1400,
  },
  // Items for ord-103 (Kaldi's Cafe)
  {
    id: 'item-5',
    orderId: 'ord-103',
    productId: 'prod-1',
    productNameEn: 'Burger Bread With Egg',
    productNameAm: 'እንቁላል የተቀባ',
    quantity: 80,
    unitPrice: 25,
    subtotal: 2000,
  },
  {
    id: 'item-6',
    orderId: 'ord-103',
    productId: 'prod-4',
    productNameEn: 'Feta Bread',
    productNameAm: 'ፈታ ዳቦ',
    quantity: 25,
    unitPrice: 35,
    subtotal: 875,
  },
  // Items for ord-104 (Stadium Fresh Burgers)
  {
    id: 'item-7',
    orderId: 'ord-104',
    productId: 'prod-2',
    productNameEn: 'Burger Bread Without Egg',
    productNameAm: 'እንቁላል ያልተቀባ',
    quantity: 140,
    unitPrice: 19, // Agreed price applied
    subtotal: 2660,
  },
  // Items for ord-105 (Olympia Corner Shop)
  {
    id: 'item-8',
    orderId: 'ord-105',
    productId: 'prod-3',
    productNameEn: 'Normal Bread',
    productNameAm: 'መደበኛ ዳቦ',
    quantity: 80,
    unitPrice: 15,
    subtotal: 1200,
  },
  // Items for ord-098
  {
    id: 'item-9',
    orderId: 'ord-098',
    productId: 'prod-1',
    productNameEn: 'Burger Bread With Egg',
    productNameAm: 'እንቁላል የተቀባ',
    quantity: 200,
    unitPrice: 22,
    subtotal: 4400,
  }
];

export const initialPayments: Payment[] = [
  // ord-101 (Total 3740): Paid 2,000 cash, 1,000 Telebirr (verified), 740 outstanding
  {
    id: 'pay-201',
    receiptNumber: 'RCT-1001',
    orderId: 'ord-101',
    customerId: 'cust-1',
    customerName: 'Solomon Tadesse (ABC Burger House)',
    amount: 2000,
    paymentMethod: 'CASH',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Owner',
    verifiedAt: `${todayStr}T07:35:00Z`,
    paymentDate: `${todayStr}T07:30:00Z`,
    notes: 'Collected cash at delivery by driver Kebede.',
    recordedBy: 'Owner',
  },
  {
    id: 'pay-202',
    receiptNumber: 'RCT-1002',
    orderId: 'ord-101',
    customerId: 'cust-1',
    customerName: 'Solomon Tadesse (ABC Burger House)',
    amount: 1000,
    paymentMethod: 'TELEBIRR',
    transactionReference: 'TB26092490812',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Owner',
    verifiedAt: `${todayStr}T07:50:00Z`,
    paymentDate: `${todayStr}T07:45:00Z`,
    notes: 'Telebirr SMS confirmed from customer manager phone.',
    recordedBy: 'Owner',
  },
  // ord-105 (Total 1200): Fully paid in cash
  {
    id: 'pay-203',
    receiptNumber: 'RCT-1003',
    orderId: 'ord-105',
    customerId: 'cust-5',
    customerName: 'Tigist Assefa (Olympia Corner Shop)',
    amount: 1200,
    paymentMethod: 'CASH',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Order Staff',
    verifiedAt: `${todayStr}T06:25:00Z`,
    paymentDate: `${todayStr}T06:20:00Z`,
    notes: 'Cash handed directly to driver Getachew.',
    recordedBy: 'Order Staff',
  },
  // ord-102 (Total 3350): Telebirr transferred by Yod Abyssinia, pending verification
  {
    id: 'pay-204',
    receiptNumber: 'RCT-1004',
    orderId: 'ord-102',
    customerId: 'cust-2',
    customerName: 'Alemayehu Kebede (Yod Abyssinia)',
    amount: 3350,
    paymentMethod: 'TELEBIRR',
    transactionReference: 'TB9988112356',
    verificationStatus: 'PENDING_VERIFICATION',
    paymentDate: `${todayStr}T08:10:00Z`,
    notes: 'Customer claims transferred via Telebirr. Need to check bakery phone SMS.',
    recordedBy: 'Order Staff',
  },
  // ord-098 (Yesterday): Customer paid 2,500 Bank Transfer verified, 1,900 remaining debt
  {
    id: 'pay-195',
    receiptNumber: 'RCT-0980',
    orderId: 'ord-098',
    customerId: 'cust-1',
    customerName: 'Solomon Tadesse (ABC Burger House)',
    amount: 2500,
    paymentMethod: 'BANK_TRANSFER',
    transactionReference: 'CBE-TXN-8871625',
    verificationStatus: 'VERIFIED',
    verifiedBy: 'Owner',
    verifiedAt: `${yesterdayStr}T11:00:00Z`,
    paymentDate: `${yesterdayStr}T10:30:00Z`,
    notes: 'CBE mobile banking transfer screenshot verified.',
    recordedBy: 'Owner',
  }
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    date: `${todayStr}T05:00:00Z`,
    amount: 12500,
    category: 'RAW_FLOUR',
    description: '10 quintals wheat flour from Kaliti Flour Factory',
    paymentMethod: 'BANK_TRANSFER',
    referenceNumber: 'INV-KL-4091',
    recordedBy: 'Owner',
    notes: 'Daily core baking supply.',
    expensePeriod: 'DAILY',
    unit: 'QUINTAL',
    quantity: 10,
    unitPrice: 1250,
  },
  {
    id: 'exp-2',
    date: `${todayStr}T06:00:00Z`,
    amount: 3600,
    category: 'RAW_EGGS',
    description: '12 crates fresh eggs for burger bun glazing',
    paymentMethod: 'CASH',
    referenceNumber: 'REC-EG-12',
    recordedBy: 'Owner',
    notes: 'Purchased from local farm supplier in Akaki.',
    expensePeriod: 'DAILY',
    unit: 'CRATE',
    quantity: 12,
    unitPrice: 300,
  },
  {
    id: 'exp-3',
    date: `${todayStr}T06:45:00Z`,
    amount: 1500,
    category: 'TRANSPORT_FUEL',
    description: 'Fuel for delivery van 2 and motorbike 1',
    paymentMethod: 'TELEBIRR',
    referenceNumber: 'TOTAL-B-991',
    recordedBy: 'Owner',
    notes: 'Total fuel station Kazanchis - 20 liters diesel.',
    expensePeriod: 'DAILY',
    unit: 'LITER',
    quantity: 20,
    unitPrice: 75,
  },
  {
    id: 'exp-4',
    date: `${yesterdayStr}T16:00:00Z`,
    amount: 1800,
    category: 'PACKAGING',
    description: 'Heavy duty plastic bread bags and packing cartons',
    paymentMethod: 'CASH',
    referenceNumber: 'PKG-302',
    recordedBy: 'Owner',
    notes: 'Supplied for 3 days of distribution.',
    expensePeriod: 'DAILY',
    unit: 'BUNDLE',
    quantity: 3,
    unitPrice: 600,
  },
  {
    id: 'exp-5',
    date: `${yesterdayStr}T17:30:00Z`,
    amount: 2400,
    category: 'RAW_CHEESE_FETA',
    description: 'Fresh feta cheese blocks for Feta Bread production',
    paymentMethod: 'CASH',
    referenceNumber: 'FETA-55',
    recordedBy: 'Owner',
    notes: 'Mama Cheese factory distribution.',
    expensePeriod: 'DAILY',
    unit: 'KG',
    quantity: 8,
    unitPrice: 300,
  },
  // Monthly Expenses (Salaries, Rent, Electricity)
  {
    id: 'exp-6',
    date: `2026-09-01T10:00:00Z`,
    amount: 45000,
    category: 'SALARIES',
    description: 'Monthly payroll for bakery bakers, assistant, and packing staff (5 employees)',
    paymentMethod: 'BANK_TRANSFER',
    referenceNumber: 'PAYROLL-SEP-26',
    recordedBy: 'Owner',
    notes: 'Paid via CBE salary transfer for September.',
    expensePeriod: 'MONTHLY',
    unit: 'MONTH',
    quantity: 1,
    unitPrice: 45000,
  },
  {
    id: 'exp-7',
    date: `2026-09-05T11:30:00Z`,
    amount: 25000,
    category: 'RENT',
    description: 'Monthly bakery building & production facility rent',
    paymentMethod: 'BANK_TRANSFER',
    referenceNumber: 'RENT-REC-0926',
    recordedBy: 'Owner',
    notes: 'Landlord receipt issued for September 2026.',
    expensePeriod: 'MONTHLY',
    unit: 'MONTH',
    quantity: 1,
    unitPrice: 25000,
  },
  {
    id: 'exp-8',
    date: `2026-09-15T14:00:00Z`,
    amount: 7800,
    category: 'UTILITIES',
    description: 'Ethiopian Electric Utility (EEU) commercial 3-phase oven electricity bill',
    paymentMethod: 'TELEBIRR',
    referenceNumber: 'EEU-BILL-88310',
    recordedBy: 'Owner',
    notes: 'Paid via Telebirr bill service.',
    expensePeriod: 'MONTHLY',
    unit: 'LUMP_SUM',
    quantity: 1,
    unitPrice: 7800,
  },
  // Yearly / Annual Expenses (License, Insurance)
  {
    id: 'exp-9',
    date: `2026-07-10T09:00:00Z`,
    amount: 14500,
    category: 'OTHER',
    description: 'Annual Trade License Renewal & City Health Sanitation Inspection Certificate',
    paymentMethod: 'BANK_TRANSFER',
    referenceNumber: 'GOV-LIC-2026-091',
    recordedBy: 'Owner',
    notes: 'Bole Sub-city Trade Bureau & Food Hygiene inspection renewal for 2026/27.',
    expensePeriod: 'YEARLY',
    unit: 'YEAR',
    quantity: 1,
    unitPrice: 14500,
  },
  {
    id: 'exp-10',
    date: `2026-08-01T15:00:00Z`,
    amount: 18000,
    category: 'MAINTENANCE',
    description: 'Annual commercial vehicle third-party & comprehensive insurance plus Bolo inspection',
    paymentMethod: 'BANK_TRANSFER',
    referenceNumber: 'NIC-INS-VAN-88',
    recordedBy: 'Owner',
    notes: 'National Insurance Company of Ethiopia (NICE) for Bakery Van 2 and Motorbike 1.',
    expensePeriod: 'YEARLY',
    unit: 'YEAR',
    quantity: 1,
    unitPrice: 18000,
  },
];

export const initialComplaints: Complaint[] = [
  {
    id: 'comp-1',
    complaintNumber: 'CMP-101',
    customerId: 'cust-1',
    customerName: 'ABC Burger House',
    orderId: 'ord-098',
    orderNumber: 'ORD-098',
    productId: 'prod-1',
    productName: 'Burger Bread With Egg (እንቁላል የተቀባ)',
    category: 'BREAD_QUALITY',
    description: '25 burger buns were slightly under-baked and too soft for grilling.',
    quantityAffected: 25,
    priority: 'HIGH',
    status: 'RESOLVED',
    resolutionType: 'REPLACEMENT',
    resolutionNotes: 'Owner sent 30 fresh properly baked buns within 45 minutes.',
    resolvedBy: 'Owner',
    resolvedAt: `${yesterdayStr}T09:15:00Z`,
    createdAt: `${yesterdayStr}T08:15:00Z`,
  },
  {
    id: 'comp-2',
    complaintNumber: 'CMP-102',
    customerId: 'cust-3',
    customerName: "Kaldi's Cafe & Bistro",
    orderId: 'ord-103',
    orderNumber: 'ORD-103',
    category: 'LATE_DELIVERY',
    description: 'Customer called stating delivery arrived 15 minutes past 08:30 AM peak rush.',
    priority: 'MEDIUM',
    status: 'UNDER_REVIEW',
    resolutionNotes: 'Checking traffic delay on Kazanchis route with driver Kebede.',
    createdAt: `${todayStr}T08:35:00Z`,
  },
  {
    id: 'comp-3',
    complaintNumber: 'CMP-103',
    customerId: 'cust-4',
    customerName: 'Stadium Fresh Burgers',
    category: 'WRONG_QUANTITY',
    description: 'Manager called complaining batch had 10 fewer buns than invoiced.',
    quantityAffected: 10,
    priority: 'HIGH',
    status: 'OPEN',
    createdAt: `${todayStr}T08:45:00Z`,
  }
];
